### ISSUE TITLE
Error message RE nil variable in http_version method

### ISSUE THREAD

**Issue by janetchang** [jnunemaker/httparty#208] opened 2013-05-09 19:56 UTC
I'm getting an error when running my User class that uses HTTParty for user authentication through an API:

**User Class**

``` ruby
require 'httparty'

class User
  include HTTParty
  base_uri 'api.someapplication.com'
  default_params :output => 'json'
  format :json

  def initialize(email, password)
    @ response = HTTParty.get('/api/v1/tokens?format=json', :query => {:email => email, :password => password})
  end

  def response
    @response.inspect
  end

  def self.find_by_email(email)
    HTTParty.get('/api/v1/users/', :query => {:email => email})
  end
end
```

user = User.new("email@email.com", "password")
puts user.response

**Error**

/Users/janet/.rvm/rubies/ruby-2.0.0-rc1/lib/ruby/2.0.0/net/http.rb:1470:in `end_transport': undefined method`http_version' for nil:NilClass (NoMethodError)
from /Users/janet/.rvm/rubies/ruby-2.0.0-rc1/lib/ruby/2.0.0/net/http.rb:1441:in `transport_request'
from /Users/janet/.rvm/rubies/ruby-2.0.0-rc1/lib/ruby/2.0.0/net/http.rb:1384:in`request'
from /Users/janet/.rvm/rubies/ruby-2.0.0-rc1/lib/ruby/2.0.0/net/http.rb:1377:in `block in request'
from /Users/janet/.rvm/rubies/ruby-2.0.0-rc1/lib/ruby/2.0.0/net/http.rb:851:in`start'
from /Users/janet/.rvm/rubies/ruby-2.0.0-rc1/lib/ruby/2.0.0/net/http.rb:1374:in `request'
from /Users/janet/.rvm/gems/ruby-2.0.0-rc1/gems/httparty-0.11.0/lib/httparty/request.rb:93:in`perform'
from /Users/janet/.rvm/gems/ruby-2.0.0-rc1/gems/httparty-0.11.0/lib/httparty.rb:463:in `perform_request'
from /Users/janet/.rvm/gems/ruby-2.0.0-rc1/gems/httparty-0.11.0/lib/httparty.rb:399:in`get'
from user.rb:14:in `login'
from user.rb:53:in`<main>'
It appears that, from the beginning of processing the GET request, HTTParty's res variable is set to nil for some reason.

It appears that, from the beginning of processing the GET request, HTTParty's res variable is set to nil for some reason. Any insights on why this is happening would be great!

**Comment by TheSmartnik** [comment] 2019-02-18 20:09
@janetchang sorry to close it without an answer, but the issue is very old and probably was fixed by now.

**Closed by TheSmartnik** 2019-02-18 20:09 UTC
