### ISSUE TITLE
Tests fail with openssl 1.1.1 with SSL_CTX_use_certificate: ee key too small (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by pravi** [jnunemaker/httparty#621] opened 2018-11-06 06:42 UTC
Originally reported here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912239 (it has full error log).

**Comment by TheSmartnik** [comment] 2019-03-20 15:09
Judging by the link you've provided the issue is fixed in 0.16.2. Thank you for reporting!

**Comment by pravi** [comment] 2019-03-20 17:02
@TheSmartnik did you confirm it is actually fixed? That bug was closed because I disabled the tests, not because the test was fixed.

**Comment by TheSmartnik** [comment] 2019-03-20 17:11
@pravi No, I didn't, actually 😕 Could you help me out?

Do I understand correctly, that to reproduce an issue. I should try to build httparty on Debian?

**Comment by pravi** [comment] 2019-03-20 17:17
@TheSmartnik that would be the easiest way to reproduce. But I assume rebuilding ruby with openssl 1.1.1 and using that ruby to run tests should reproduce it. I can provide ssh access to a debian test machine if you like.

**Comment by TheSmartnik** [comment] 2019-03-20 17:19
@pravi thanks!

> that would be the easiest way to reproduce. But I assume rebuilding ruby with openssl 1.1.1 and using that ruby to run tests should reproduce it

Thanks. I'll try and let you know

**Closed** 2019-03-21 10:52 UTC
